# config validation - https://config.travis-ci.com/explore
language: swift
os: osx
osx_image: xcode11.2
xcode_sdk: iphonesimulator13.2.2
cache: bundler
branches:
  only:
    - /.*/
before_install:
  - eval `ssh-agent -s`
  - >-
    openssl aes-256-cbc 
    -K $encrypted_1d562ea9f9b4_key 
    -iv $encrypted_1d562ea9f9b4_iv 
    -in ./scripts/github_certs_deploy_key.enc 
    -out github_certs_deploy_key 
    -d
  - chmod 600 github_certs_deploy_key
  - ssh-add -K github_certs_deploy_key
before_script: 'echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config'
jobs:
  include:
  # - stage: Tests
  #   name: Unit Tests
  #   script: fastlane unit_test

  # - stage: Tests
  #   name: UI Tests
  #   script: fastlane ui_test

  - stage: App Distribution
    name: Firebase
    if: branch =~ /^(master|release\/[0-9]\.[0-9]\.[0-9])/
    # script: fastlane firebase_distribution
    script: git clone --verbose git@github.com:paulpires/certs.git
    # script: git clone --verbose https://github.com/paulpires/certs.git
