# https://docs.fastlane.tools/actions

default_platform(:ios)

ENV['FIREBASE_TOKEN'] = '1//03zZkLYmgP70oCgYIARAAGAMSNwF-L9IrhsHaAEnSnpr0OkXso4W18Au1q2LWTr81AofZJEjfqX2Rr6-zdsu2V0m1oLFhh7_A2yo'
artifacts = './artifacts/'

lane :unit_test do
	run_tests(
		workspace: 'photo-cast.xcworkspace',
		scheme: 'photo-cast',
		device: 'iPhone 11 Pro Max (13.2.2)',
		code_coverage: true,
		output_directory: "#{artifacts}/unit_tests/",
		result_bundle: "#{artifacts}/unit_tests/"
	)
end

lane :ui_test do 
	run_tests(
		workspace: 'photo-cast.xcworkspace',
		scheme: 'photo-cast-UITests',
		device: 'iPad Pro (12.9-inch) (3rd generation) (13.2.2)',
		output_directory: "#{artifacts}/ui_tests/",
		result_bundle: "#{artifacts}/ui_tests/"
	)
end

lane :archive_ipa do
	build_app(
		workspace: 'photo-cast.xcworkspace',
		configuration: 'Debug',
		scheme: 'photo-cast',
		export_method: 'development',
		output_name: 'photo-cast',
		output_directory: "#{artifacts}",
		clean: true
	)
end

lane :distribute do
    firebase_app_distribution(
        app: "1:120925620508:ios:e2b67bca7eb613d25112d9",
        release_notes: "Lots of amazing new features to test out!",
        firebase_cli_path: "/usr/local/bin/firebase",
        ipa_path: "#{artifacts}/photo-cast.ipa",
        groups: 'regression'
    )
end
